### PR TITLE
Expand upon ElytraFeatures

### PR DESCRIPTION
**Pull request by Protonull**

### CODE REVIEW

**Comment by Protonull** [comment]
This PR adds three configurable features:

- Disable firework-boosting while in combat

- Limit firework-boosting to explosive fireworks

- Damage the flier over time when gliding above world height

**Comment by KaloHG** [comment]
all of these are actually decent suggestions, however I think that the explosive only bit should be disabled on live.

**Comment by Metriximor** [comment]
Explosive fireworks only on elytras is a bit of a meme. Fireworks are already expensive enough.

**Comment by Protonull** [comment]
Oh yeah, the explosive firework was a funny meme I came up while drinking, just thinking about all the rich players zooming around in the sky ticking their armour durability and chugging potions. It brings me joy. But you're probably right it's best not to activate it on Civclassic.

**Pull request merged**
